version: '3'

networks:
  django-network:
    driver: bridge

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - django-network
  sorterbot_control:
    image: sorterbot_control:latest
    ports:
      - $EXT_PORT:8000
    networks:
      - django-network
    depends_on:
      - redis
    environment:
      - MIGRATE=$MIGRATE
      - MODE=$MODE
      - DEPLOY_REGION=$DEPLOY_REGION
    env_file:
      - sbc_server/.env
#  Uncomment for hot code reload
    volumes:
      - "./sbc_server/core:/sbc_server/core"
      - "./sbc_server/sbc_server:/sbc_server/sbc_server"
      # - "./sbc_server/.env:/sbc_server/.env"
      - "~/.aws:/root/.aws"
