version: '3'

networks:
  django-network:
    driver: bridge

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - django-network
  sorterbot_control:
    image: sorterbot_control:latest
    ports:
      - 80:8000
      # - 8000:8000
    networks:
      - django-network
    depends_on:
      - redis
    environment:
      - MIGRATE
      - DISABLE_AWS=$DISABLE_AWS
      - PG_PASS=$PG_PASS
#  Uncomment for hot code reload
    volumes:
      - "./sbc_server/core:/sbc_server/core"
      - "./sbc_server/sbc_server:/sbc_server/sbc_server"
