# Generated by Django 3.0.5 on 2020-04-13 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arm_id', models.CharField(max_length=20)),
                ('arm_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('before_img_url', models.CharField(max_length=300)),
                ('after_img_url', models.CharField(max_length=300)),
                ('logs_base_url', models.CharField(max_length=300)),
                ('log_filenames', models.TextField()),
                ('arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorterbot_control_panel.Arm')),
            ],
        ),
    ]
