# Generated by Django 3.0.5 on 2020-04-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorterbot_control_panel', '0001_initial_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='UI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud_status', models.CharField(max_length=20)),
            ],
        ),
    ]
