# Generated by Django 3.0.5 on 2020-04-18 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sorterbot_control_panel', '0004_auto_20200417_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=40)),
                ('step', models.CharField(max_length=40)),
                ('asctime', models.CharField(max_length=40)),
                ('created', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('levelname', models.CharField(max_length=40)),
                ('msg', models.CharField(max_length=40)),
                ('pathname', models.CharField(max_length=40)),
                ('lineno', models.CharField(max_length=40)),
                ('arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sorterbot_control_panel.Arm')),
            ],
        ),
    ]
