# Generated by Django 3.0.5 on 2020-04-18 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorterbot_control_panel', '0006_auto_20200418_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='arm_id',
            new_name='arm',
        ),
        migrations.RenameField(
            model_name='log',
            old_name='session_id',
            new_name='session',
        ),
    ]
