# Generated by Django 3.0.5 on 2020-04-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorterbot_control_panel', '0008_auto_20200418_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='levelname',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='log',
            name='lineno',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='log',
            name='msg',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='log',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='log',
            name='pathname',
            field=models.CharField(max_length=200),
        ),
    ]
