# Generated by Django 3.0.5 on 2020-04-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorterbot_control_panel', '0009_auto_20200418_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='enabled_log_types',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
