# Generated by Django 3.0.5 on 2020-04-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorterbot_control_panel', '0011_ui_open_logs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ui',
            name='cloud_status',
        ),
        migrations.RemoveField(
            model_name='ui',
            name='start_session',
        ),
        migrations.AddField(
            model_name='ui',
            name='arms_to_start',
            field=models.TextField(default=[]),
            preserve_default=False,
        ),
    ]
