# Generated by Django 3.0.5 on 2020-04-24 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorterbot_control_panel', '0012_auto_20200423_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='enabled_log_types',
            field=models.TextField(default='[]'),
        ),
    ]
