# Generated by Django 3.0.5 on 2020-05-01 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arm',
            fields=[
                ('arm_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('last_online', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arms_to_start', models.TextField()),
                ('open_logs', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=40)),
                ('status', models.CharField(blank=True, max_length=20)),
                ('before_img_url', models.CharField(blank=True, max_length=300)),
                ('after_img_url', models.CharField(blank=True, max_length=300)),
                ('logs_base_url', models.CharField(blank=True, max_length=300)),
                ('log_filenames', models.TextField(blank=True)),
                ('enabled_log_types', models.TextField(default='[]')),
                ('arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Arm')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(max_length=40)),
                ('asctime', models.CharField(max_length=40)),
                ('created', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=20)),
                ('levelname', models.CharField(max_length=10)),
                ('msg', models.TextField()),
                ('pathname', models.CharField(max_length=200)),
                ('lineno', models.CharField(max_length=10)),
                ('arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Arm')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Session')),
            ],
        ),
    ]
