# Generated by Django 3.0.5 on 2020-05-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200503_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ui',
            name='arms_to_start',
            field=models.TextField(default='[]'),
        ),
    ]
